server:
  port: "9090"
  mode: "debug" # debug, release
  read_timeout: 60
  write_timeout: 60

# 远程数据库配置
database:
  host: "your-remote-db-host.com"  # 替换为你的远程数据库地址
  port: 5432                        # 远程PostgreSQL端口（通常是5432）
  user: "bblearning"
  password: "your-remote-db-password"  # 替换为远程数据库密码
  dbname: "bblearning_dev"
  sslmode: "require"                # 远程连接建议使用SSL
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# 远程Redis配置
redis:
  host: "your-remote-redis-host.com"  # 替换为你的远程Redis地址
  port: 6379                           # 远程Redis端口（通常是6379）
  password: "your-redis-password"      # 如果有密码，替换这里
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expiration: 3600 # seconds

ai:
  provider: "openai" # openai, claude
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7

# 远程MinIO配置（或使用云存储服务）
minio:
  endpoint: "your-remote-minio.com:9000"  # 替换为远程MinIO地址
  access_key: "your-access-key"           # 替换为访问密钥
  secret_key: "your-secret-key"           # 替换为密钥
  use_ssl: true                           # 远程连接建议使用SSL
  bucket: "bblearning"

ocr:
  provider: "tencent"
  region: "ap-guangzhou"
  max_image_size: 4194304 # 4MB
  timeout: 30 # seconds
