server:
  port: "9090"
  mode: "debug" # debug, release
  read_timeout: 60
  write_timeout: 60

database:
  host: "postgres"
  port: 5432
  user: "bblearning"
  password: "bblearning_dev_password"
  dbname: "bblearning_dev"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expiration: 3600 # seconds

ai:
  provider: "openai" # openai, claude
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7

minio:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin123"
  use_ssl: false
  bucket: "bblearning"
