server:
  port: "9090"
  mode: "debug" # debug, release
  read_timeout: 60
  write_timeout: 60

database:
  host: "localhost"
  port: 5433
  user: "bblearning"
  password: "bblearning_dev_password"
  dbname: "bblearning_dev"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: "localhost"
  port: 6380
  password: ""
  db: 0

jwt:
  secret: "your-secret-key-change-in-production"
  expiration: 3600 # seconds

ai:
  provider: "openai" # openai, claude
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin123"
  use_ssl: false
  bucket: "bblearning"

ocr:
  provider: "tencent" # tencent, baidu, aliyun
  # Tencent Cloud OCR credentials (stored in database via api_keys table)
  # Use api_key_service to manage credentials securely
  region: "ap-guangzhou"
  max_image_size: 4194304 # 4MB
  timeout: 30 # seconds
