name: iOS Release

on:
  push:
    tags:
      - 'ios-v*'

jobs:
  release:
    name: Build and Release
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: ios/BBLearning

      - name: Install Fastlane
        working-directory: ios/BBLearning
        run: |
          gem install bundler
          bundle install

      - name: Setup certificates
        working-directory: ios/BBLearning
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: |
          bundle exec fastlane setup_signing

      - name: Build and upload to TestFlight
        working-directory: ios/BBLearning
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
        run: |
          bundle exec fastlane beta

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: iOS Release ${{ github.ref }}
          body: |
            iOS应用新版本发布

            ## 更新内容
            - 查看完整更新日志

            ## TestFlight
            已上传至TestFlight，请等待Apple审核
          draft: false
          prerelease: false

      - name: Notify on failure
        if: failure()
        run: |
          echo "Build failed! Please check the logs."
          # 这里可以添加钉钉或企业微信通知
