name: iOS CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'ios/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Install dependencies
        working-directory: ios/BBLearning
        run: |
          # Install Ruby dependencies
          gem install bundler
          bundle install

          # Resolve Swift Package Dependencies
          xcodebuild -resolvePackageDependencies

      - name: Run SwiftLint
        working-directory: ios/BBLearning
        run: |
          if which swiftlint >/dev/null; then
            swiftlint --reporter github-actions-logging
          else
            echo "SwiftLint not installed, skipping..."
          fi

      - name: Build
        working-directory: ios/BBLearning
        run: |
          xcodebuild clean build \
            -scheme BBLearning \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Run tests
        working-directory: ios/BBLearning
        run: |
          xcodebuild test \
            -scheme BBLearning \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
            -configuration Debug \
            -enableCodeCoverage YES \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: ios
          name: ios-coverage

  lint:
    name: Code Quality
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        working-directory: ios/BBLearning
        run: swiftlint lint --reporter github-actions-logging --strict

  analyze:
    name: Static Analysis
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Run static analyzer
        working-directory: ios/BBLearning
        run: |
          xcodebuild analyze \
            -scheme BBLearning \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
